// Generated from the HashtagCMS Workflows directive manifest — DO NOT EDIT BY HAND.
// Regenerate: ./mvnw test -Dtest=ClientModelGeneratorTest -Dcodegen.write=true

/// Every directive type the server can emit, with its category and negotiation fallback.
public enum WorkflowDirectiveType: String, CaseIterable {
    case toast = "toast"
    case alert = "alert"
    case snackbar = "snackbar"
    case banner = "banner"
    case haptic = "haptic"
    case playSound = "play_sound"
    case showLoader = "show_loader"
    case hideLoader = "hide_loader"
    case progress = "progress"
    case confetti = "confetti"
    case confirm = "confirm"
    case coachmark = "coachmark"
    case setFieldError = "set_field_error"
    case navigate = "navigate"
    case goBack = "go_back"
    case switchTab = "switch_tab"
    case scrollTo = "scroll_to"
    case openUrl = "open_url"
    case deepLink = "deep_link"
    case openSheet = "open_sheet"
    case dismissSheet = "dismiss_sheet"
    case openModal = "open_modal"
    case dismissModal = "dismiss_modal"
    case replace = "replace"
    case popToRoot = "pop_to_root"
    case callPhone = "call_phone"
    case openEmail = "open_email"
    case openMap = "open_map"
    case openSettings = "open_settings"
    case mutateCart = "mutate_cart"
    case updateBadge = "update_badge"
    case setWishlist = "set_wishlist"
    case startCheckout = "start_checkout"
    case clearCart = "clear_cart"
    case updateQuantity = "update_quantity"
    case notifyBackInStock = "notify_back_in_stock"
    case trackOrder = "track_order"
    case renderPhotos = "render_photos"
    case renderList = "render_list"
    case showWelcome = "show_welcome"
    case renderComponent = "render_component"
    case updateComponent = "update_component"
    case setTheme = "set_theme"
    case setLocale = "set_locale"
    case updateState = "update_state"
    case setValue = "set_value"
    case refresh = "refresh"
    case reload = "reload"
    case invalidateCache = "invalidate_cache"
    case setAuth = "set_auth"
    case clearAuth = "clear_auth"
    case requestBiometric = "request_biometric"
    case copyToClipboard = "copy_to_clipboard"
    case share = "share"
    case requestReview = "request_review"
    case requestPermission = "request_permission"
    case scheduleNotification = "schedule_notification"
    case addToCalendar = "add_to_calendar"
    case scanQr = "scan_qr"
    case scanBarcode = "scan_barcode"
    case downloadFile = "download_file"
    case getLocation = "get_location"
    case trackEvent = "track_event"
    case openPaymentSheet = "open_payment_sheet"
    case addPaymentMethod = "add_payment_method"
    case showPaywall = "show_paywall"
    case runWorkflow = "run_workflow"
    case delay = "delay"
    case emitEvent = "emit_event"
    case setFlag = "set_flag"
    case registerPush = "register_push"
    case shareReferral = "share_referral"

    public var category: String {
        switch self {
        case .toast: return "feedback"
        case .alert: return "feedback"
        case .snackbar: return "feedback"
        case .banner: return "feedback"
        case .haptic: return "feedback"
        case .playSound: return "feedback"
        case .showLoader: return "feedback"
        case .hideLoader: return "feedback"
        case .progress: return "feedback"
        case .confetti: return "feedback"
        case .confirm: return "feedback"
        case .coachmark: return "feedback"
        case .setFieldError: return "feedback"
        case .navigate: return "navigation"
        case .goBack: return "navigation"
        case .switchTab: return "navigation"
        case .scrollTo: return "navigation"
        case .openUrl: return "navigation"
        case .deepLink: return "navigation"
        case .openSheet: return "navigation"
        case .dismissSheet: return "navigation"
        case .openModal: return "navigation"
        case .dismissModal: return "navigation"
        case .replace: return "navigation"
        case .popToRoot: return "navigation"
        case .callPhone: return "navigation"
        case .openEmail: return "navigation"
        case .openMap: return "navigation"
        case .openSettings: return "navigation"
        case .mutateCart: return "cart"
        case .updateBadge: return "cart"
        case .setWishlist: return "cart"
        case .startCheckout: return "cart"
        case .clearCart: return "cart"
        case .updateQuantity: return "cart"
        case .notifyBackInStock: return "cart"
        case .trackOrder: return "cart"
        case .renderPhotos: return "content"
        case .renderList: return "content"
        case .showWelcome: return "content"
        case .renderComponent: return "content"
        case .updateComponent: return "content"
        case .setTheme: return "content"
        case .setLocale: return "content"
        case .updateState: return "state"
        case .setValue: return "state"
        case .refresh: return "state"
        case .reload: return "state"
        case .invalidateCache: return "state"
        case .setAuth: return "auth"
        case .clearAuth: return "auth"
        case .requestBiometric: return "auth"
        case .copyToClipboard: return "device"
        case .share: return "device"
        case .requestReview: return "device"
        case .requestPermission: return "device"
        case .scheduleNotification: return "device"
        case .addToCalendar: return "device"
        case .scanQr: return "device"
        case .scanBarcode: return "device"
        case .downloadFile: return "device"
        case .getLocation: return "device"
        case .trackEvent: return "analytics"
        case .openPaymentSheet: return "payments"
        case .addPaymentMethod: return "payments"
        case .showPaywall: return "payments"
        case .runWorkflow: return "flow"
        case .delay: return "flow"
        case .emitEvent: return "flow"
        case .setFlag: return "flow"
        case .registerPush: return "growth"
        case .shareReferral: return "growth"
        }
    }

    public var fallback: WorkflowDirectiveType? {
        switch self {
        case .toast: return nil
        case .alert: return .toast
        case .snackbar: return .toast
        case .banner: return .toast
        case .haptic: return nil
        case .playSound: return nil
        case .showLoader: return nil
        case .hideLoader: return nil
        case .progress: return nil
        case .confetti: return nil
        case .confirm: return .alert
        case .coachmark: return .toast
        case .setFieldError: return .toast
        case .navigate: return nil
        case .goBack: return nil
        case .switchTab: return .navigate
        case .scrollTo: return nil
        case .openUrl: return nil
        case .deepLink: return .navigate
        case .openSheet: return .navigate
        case .dismissSheet: return nil
        case .openModal: return .openSheet
        case .dismissModal: return nil
        case .replace: return .navigate
        case .popToRoot: return .goBack
        case .callPhone: return .toast
        case .openEmail: return .openUrl
        case .openMap: return .openUrl
        case .openSettings: return nil
        case .mutateCart: return .toast
        case .updateBadge: return nil
        case .setWishlist: return .toast
        case .startCheckout: return .navigate
        case .clearCart: return .toast
        case .updateQuantity: return .mutateCart
        case .notifyBackInStock: return .toast
        case .trackOrder: return .navigate
        case .renderPhotos: return .toast
        case .renderList: return .toast
        case .showWelcome: return .banner
        case .renderComponent: return .renderList
        case .updateComponent: return nil
        case .setTheme: return nil
        case .setLocale: return nil
        case .updateState: return nil
        case .setValue: return nil
        case .refresh: return nil
        case .reload: return nil
        case .invalidateCache: return nil
        case .setAuth: return nil
        case .clearAuth: return nil
        case .requestBiometric: return nil
        case .copyToClipboard: return nil
        case .share: return .copyToClipboard
        case .requestReview: return nil
        case .requestPermission: return nil
        case .scheduleNotification: return nil
        case .addToCalendar: return nil
        case .scanQr: return nil
        case .scanBarcode: return nil
        case .downloadFile: return .openUrl
        case .getLocation: return nil
        case .trackEvent: return nil
        case .openPaymentSheet: return .navigate
        case .addPaymentMethod: return .navigate
        case .showPaywall: return .navigate
        case .runWorkflow: return nil
        case .delay: return nil
        case .emitEvent: return nil
        case .setFlag: return nil
        case .registerPush: return nil
        case .shareReferral: return .share
        }
    }
}
